# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
